Add SetWinEventHook function
AArnott/pinvoke pull request #295
Opened 2016-10-01 18:23 UTC by zabulus

I'll add more documentation for ```WindowsEventHookType``` values.

2016-10-01 20:42 UTC, vbfox requested changes
Except for the delegate name, the rest LGTM.

2016-10-01 20:42 UTC, vbfox commented on src/User32.Desktop/User32.cs
> +        public delegate void WinEventProcDelegate(
The name should be just `WinEventProc` as it exists under this name in MSDN ( https://msdn.microsoft.com/en-us/library/windows/desktop/dd373885(v=vs.85).aspx )

2016-10-01 20:59 UTC, zabulus commented on src/User32.Desktop/User32.cs
> +        public delegate void WinEventProcDelegate(
Fixed.
BTW, for ```SetWindowsHookEx``` name of delegate is "WindowsHookDelegate" ( https://github.com/zabulus/pinvoke/blob/7a4af64d379380445bdd9127854ca12b3c7171e9/src/User32.Desktop/User32.cs#L85 )

2016-10-01 21:26 UTC, vbfox commented on src/User32.Desktop/User32.cs
> +        public delegate void WinEventProcDelegate(
Yes sadly `WindowsHookDelegate` is as it is until we move the major version or we'll break semver :(

2016-10-01 21:27 UTC, vbfox approved these changes

2016-10-02 21:03 UTC, AArnott commented
Thank you for the contribution, and @vbfox for vetting it.

2016-10-02 21:03 UTC, merged