Add ServiceType SERVICE_NO_CHANGE
AArnott/pinvoke pull request #327
Opened 2017-05-24 19:12 UTC by aluferYochay

2017-05-24 20:33 UTC, vbfox reviewed
Hi, thanks for your contribution. I think I agree that `SERVICE_NO_CHANGE` should be part of the enum, a separate constant would work but it would force a cast.

@AArnott What do you think ?

It seem that `SERVICE_NO_CHANGE` can be used on 3 enums, if we go with this change would you mind changing the 2 others (`ServiceErrorControl` & `ServiceStartType`) ?

2017-05-24 20:34 UTC, vbfox approved these changes

2017-05-24 20:34 UTC, vbfox commented on src/AdvApi32/AdvApi32+ServiceType.cs
> +
I think that it's this line that contains whitespace that is breaking the CI build for this PR

2017-05-24 22:57 UTC, AArnott commented
I agree with @vbfox that adding the value to each of the 3 enum's is probably the way to go.

2017-05-24 22:57 UTC, AArnott requested changes

2017-05-24 22:57 UTC, AArnott commented on src/AdvApi32/AdvApi32+ServiceType.cs
> +            SERVICE_NO_CHANGE = 0xFFFFFFFF
Can you also add a trailing comma to this last enum, so that the next time an enum value is added, it doesn't have to change this line?

2017-05-25 09:14 UTC, aluferYochay commented
What it means that the SERVICE_NO_CHANGE is not part of the declared API ?

2017-05-25 14:34 UTC, AArnott commented
@aluferYochay It looks from your commits that you're not sure how to get the build to work. I have two suggestions:

1. Use the Format Document command in VS. That generally trims the whitespace and formats the code so that StyleCop is happy and should help you get the build to pass.
1. Use the build.ps1 script in the root of the repo to check that the build will succeed before committing and pushing. It should give you a pretty accurate idea of whether it will work without having to run appveyor.

Squash your commits and force push when you get it working so we get a reasonably clean set of commits to merge.

2017-05-25 14:34 UTC, AArnott commented
Thank you for your contribution, @aluferYochay

2017-05-28 10:21 UTC, aluferYochay commented
Hi 
I have few errors when running the build script, different from "not part of the declared API.." 
[out.txt](https://github.com/AArnott/pinvoke/files/1034091/out.txt)

Can you advice on how to resolve ?

2017-05-28 13:35 UTC, AArnott commented
Did you run build.ps1 without parameters, or did you run it with `-Restore` at least once?

2017-05-28 14:16 UTC, aluferYochay commented
I ran it with restore..

2017-05-28 16:06 UTC, AArnott commented
Hmmm... I don't know what the problem would be then. I'm preparing a commit to fix the remaining issues.

2017-05-28 17:12 UTC, AArnott approved these changes

2017-05-28 17:25 UTC, merged

2017-05-28 17:25 UTC, AArnott commented
Thank you for your contribution, @aluferYochay