Added AttachThreadInput to User32 namespace.
AArnott/pinvoke pull request #348
Opened 2017-09-04 07:21 UTC by BarryNolte

Added the DllImport and api signature to the User32 namespace.

2017-09-04 08:59 UTC, vbfox requested changes

2017-09-04 08:59 UTC, vbfox commented on src/User32/User32.cs
> +        public static extern bool AttachThreadInput(uint idAttach, uint idAttachTo, [MarshalAs(UnmanagedType.Bool)] bool fAttach);
We don't use `uint` in type signatures prefering to always expose the signed type (so `int` here)

2017-09-04 08:59 UTC, vbfox commented on src/User32/User32.cs
> +        [DllImport("user32.dll", EntryPoint = "AttachThreadInput")]
`"user32.dll"` should be `nameof(User32)`, no need to specify the `EntryPoint` and the function use `SetLastError` for it's error signaling so it should have `, SetLastError = true`.

2017-09-04 09:00 UTC, vbfox commented
Thanks for the PR !

Just a few formatting fixed and it's all good for me 😉

2017-09-04 09:01 UTC, vbfox requested changes

2017-09-04 09:01 UTC, vbfox commented on src/User32/User32.cs
> +        // [DllImport(nameof(User32), SetLastError = true)]
That declaration and signature actually looks good :)

If only it wasn't commented

2017-09-06 00:00 UTC, AArnott commented on src/User32/User32.cs
> +        /// <returns>If the function succeeds, the return value is nonzero. If the function fails, the return value is zero.To get extended error information, call GetLastError. Windows Server2003 an
You are missing several spaces between words and sentences. Likely this happened when you copied and pasted the MSDN docs and C# "formatted" the text by removing spaces after periods. It's important when you copy and paste that after paste, you immediately hit Undo to revert the formatting changes (but keep the paste).

2017-09-06 07:16 UTC, vbfox approved these changes

2017-09-06 13:40 UTC, AArnott approved these changes
Awesome. Thank you!

2017-09-06 13:40 UTC, merged