Update User32::WinEventProc and MSCorEE::GetVersionFromProcess
AArnott/pinvoke pull request #397
Opened 2018-07-14 02:42 UTC by joerohde

User32: Update WinEventProc - Runtime Issue
- Param 1 is IntPtr - Income parm should be be SafeEvent...
MSCorEE: Update GetVersionFromProcess - Compile Issue
- Can't cast [] to * without marking method unsafe and using a 'fixed' scope block.

2018-09-07 04:00 UTC, AArnott requested changes
I don't understand why either of these changes are needed. Can you elaborate?

2018-09-07 04:00 UTC, AArnott commented on src/User32/User32.cs
> +            IntPtr hWinEventHook,
Why are we switching from a SafeHandle to an IntPtr here? From the docs, it seems this value comes from `SetWinEventHook`, which (still) returns a `SafeEventHookHandle`, so isn't it both easier and safer to keep this as a `SafeEventHookHandle` here as well?

2018-09-07 04:00 UTC, AArnott commented on src/MSCorEE/MSCorEE.Helpers.cs
> +
Why does this change need to be made? There is already an overload of `GetVersionFromProcess` that basically does this that we were calling before you made this change:

```cs
        public static unsafe HResult GetVersionFromProcess(SafeHandle hProcess, char[] pVersion, int cchBuffer, out int dwLength)
        {
            fixed (char *pVersionLocal = pVersion)
            {
                HResult result = GetVersionFromProcess(hProcess, pVersionLocal, cchBuffer, out dwLength);
                return result;
            }
        }
```

This overload is generated during the build, so you wouldn't see it in checked in source code, but in VS after building once you can Go To Definition on this call and see the generated code.

2018-09-07 20:45 UTC, vbfox commented on src/User32/User32.cs
> +            IntPtr hWinEventHook,
It produce a runtime error, the marshaller currently doesn't handle theses

> 'Cannot marshal 'parameter #1': SafeHandles cannot be marshaled from unmanaged to managed.'

Still seem to be that case in coreclr https://github.com/dotnet/coreclr/blob/2b50bba8131acca2ab535e144796941ad93487b7/src/vm/ilmarshalers.cpp#L2866 I don't know what make this case more special than an out parameter but well it's like that for now

2019-12-23 04:30 UTC, AArnott approved these changes
I reverted the unnecessary change and will take the rest. Thanks.

2019-12-23 04:30 UTC, AArnott commented on src/MSCorEE/MSCorEE.Helpers.cs
> +
No reason I guess. I'm reverting this change.

2019-12-23 04:30 UTC, AArnott approved these changes

2019-12-23 04:57 UTC, merged

2020-05-23 21:01 UTC, FDB-Fakim commented
Is there a reason https://github.com/AArnott/pinvoke/commit/9476c5cc9d067f78b45e7565701059286b9ac42a isn't included in PInvoke.User32.0.6.6.nupkg?

2020-05-23 21:59 UTC, AArnott commented
@FDB-Fakim Yes: that release came out before this PR completed. :)

2020-05-23 22:03 UTC, AArnott commented
I think what you mean to ask is "Is there a reason there hasn't been a release since this PR was merged?"

And the answer to that would be "not particularly." I suppose it is time to release another one. I'll prepare one.