Add NativeOverlapped overloads
AArnott/pinvoke pull request #495
Opened 2020-07-06 19:55 UTC by qmfrederik

In line with #419, and also based on my own experience, add overloads which use the `System.Threading.NativeOverlapped` struct instead of `Kernel32+OVERLAPPED`. .NET has built-in support for overlapped I/O, so let's use that instead of rolling our own.

In line with the guidance in #487, obsolete these types/overloads instead of removing them.

Closes #419

2020-07-06 20:12 UTC, qmfrederik commented
Hmm, having overloads with both `OVERLAPPED*` and `NativeOverlapped*` structs generates conflicts (the code generator would generate two identical overloads with `IntPtr` parameters), so I removed `OVERLAPPED*` for now. Happy to revisit if needed.

2020-07-08 13:44 UTC, AArnott commented
This is a binary breaking change. AFAIK we haven't introduced any lately, so I hesitate to take one now unless we're prepared to do a bunch of others as well to minimize the number of releases with breaking changes over time. #288 tracks many ideas for breaking changes.
We could perhaps start a branch with changes like these and merge them all at once, although I'm concerned about merge conflicts too, so I prefer to keep a list of ideas for changes and then we can work on them all at once and merge more quickly.

2020-07-08 14:03 UTC, qmfrederik commented
@AArnott Alternatively, we can add this as a new overload in a `.Helper.cs` file; but at the moment the code generators would generate an `IntPtr`-based overload, which would cause conflicts.

2020-07-08 15:15 UTC, AArnott commented
What if we just add conversion operators to our struct so it can be cast to the other one?

2020-07-16 20:16 UTC, AArnott requested changes
I've heard from the .NET interop folks that each p/invoke function has a fixed cost and they were very happy to hear that we had just one per Win32 function and all our overloads were just thunks into that same one. Rather than creating new p/invokes for the same function, can you add methods to the helper file that simply re-cast the pointer from `NativeOverlapped*` to `OVERLAPPED*`? That way we have more performant, less memory hungry code.

2020-07-17 14:44 UTC, AArnott requested changes
Looks perfect. But we could trim down the xml doc comment weight of it significantly. See my tip.

2020-07-17 14:44 UTC, AArnott commented on src/Kernel32/Kernel32.Helpers.cs
> +        /// </returns>
Do you know you don't have to copy this from the other overload? 
You can replace it all with this:
```cs
/// <inheritdoc cref="CancelIoEx(SafeObjectHandle, OVERLAPPED*)" />
```

Then, if you hover over your new method's name or its parameters, you'll see that the docs all magically show up.

2020-07-19 18:57 UTC, AArnott approved these changes

2020-07-19 19:12 UTC, merged